CREATE DATABASE IF NOT EXISTS detalls;
USE detalls;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    imagen VARCHAR(255) NULL
);
CREATE TABLE pagos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    productos VARCHAR(255) NOT NULL,
    ciudad VARCHAR(100),
    cp VARCHAR(10),
    provincia VARCHAR(100),
    total DECIMAL(10,2) NOT NULL
);
